### ISSUE TITLE
didnt but after 0.39 but all account banned today

### ISSUE THREAD

**Issue by wkeongkhor** [Lunat1q/Catchem-PoGo#2094] opened 2016-09-30 09:15 UTC
didnt bot after 0.39 but all account banned today ,anyone banned please leave your message here

**Comment by Horizonne** [comment] 2016-09-30 09:24
Banned upon login 30 mins ago. Confirmed =(

**Comment by easonfu** [comment] 2016-09-30 09:36
Two got permanently banned around 2hrs ago. Sigh...

**Comment by ftmk25** [comment] 2016-09-30 09:37
I just don't open it since 3 days because of that 
I expected that this would happen

**Comment by TemhAAhmeT** [comment] 2016-09-30 09:51
all accounts get banned

**Comment by jahwulf935** [comment] 2016-09-30 09:59
2 accounts banned. still got 4 more which i didn't use since around three weeks ago..

**Comment by WsTs** [comment] 2016-09-30 10:17
All my account still can on, not yet ban. I stop botting once the App is being forced update to 0.39.1 
Anyone same situation with me?

**Comment by SkyWalter** [comment] 2016-09-30 10:45
Banned too.

**Comment by ssamadiG0** [comment] 2016-09-30 10:46
Banned too 5 accounts

**Comment by steurdust** [comment] 2016-09-30 10:52
Had 3 account, left my lvl 32 running last night and he is now banned ;(

**Comment by jeversonjoao** [comment] 2016-09-30 10:53
my acc lvl 36 banned now.

WTF!

**Comment by tyu36** [comment] 2016-09-30 10:54
how do you know the account is banned? Login with the phone to get the banned message?

**Comment by jeversonjoao** [comment] 2016-09-30 10:55
Just a message with error in login

**Comment by era12345** [comment] 2016-09-30 10:55
if u encountered failed to retrieve data from server blah blah blah

**Comment by jeversonjoao** [comment] 2016-09-30 10:57
I have no idea what was the criterion used to perform this ban.
Never leave the same locality, not used teleportation. Nothing more.
They made some sort of new ban this time.

**Comment by era12345** [comment] 2016-09-30 11:00
i've checked my account (lvl28) just now but still working. i stop using the bot once i've read the announcement and played the account manually .

**Comment by era12345** [comment] 2016-09-30 11:04
same thing happen with the accounts who used hackemon. you may check their site. most of them were BANNED.

**Comment by tyu36** [comment] 2016-09-30 11:07
the failure to authenticate message?  Is your phone rooted?  If so, it still cannot conclude the ban.

My scenario is at the moment of v0.35, I can play with my google account but with the tutu version of 0.35, it waits infinitely with the same google account.  If I use another new google account with the tutu version, it also waits infinitely.  New means never play the game before and never run the bot.  If I use a PTC account, the tutu version is working.

In v0.39, the scenario just changes from waiting infinitely to show the authentication error after 2 minutes.
So what can be concluded?

**Comment by BSwazZ** [comment] 2016-09-30 11:36
![screenshot_20160930-133153](https://cloud.githubusercontent.com/assets/20690071/18990520/d03fdf8e-8712-11e6-816a-5727eb568a68.png)

i started on my phone and....

**Comment by LugiaRX** [comment] 2016-09-30 11:45
no bans yet. waiting and praying.

**Comment by alanearl** [comment] 2016-09-30 11:50
Can the developers integrate the catchem on bluestack so that it is not API dependent?

**Comment by hotmetal007** [comment] 2016-09-30 12:21
im not ban :D!, sorry for you guys :(, but for the bots, ban means nothing! go bots master race!

**Comment by tony031** [comment] 2016-09-30 12:26
Is there anybody like me never get a 10km egg for catchem?

**Comment by hotmetal007** [comment] 2016-09-30 12:39
i got 4 10km egg 
1=snorlax 
2,3,4= Evee xD!

**Comment by alfath2016** [comment] 2016-09-30 12:46
Alhamdulillah...just checked all my 5 accounts still survived. Lvl 34 33 33 28 27.  Maybe just luck or waiting the dead angel calling.

Cheer up guys..this is just a game. For me the most fun of this game is catch and run within boter/dev and niantic.

**Comment by tony031** [comment] 2016-09-30 12:59
to hotmetal007... really? I thought that was some kind of flag for banning because I never get a 10km egg for all my Lvl 26 in catchem.

**Comment by ArchangelBr** [comment] 2016-09-30 13:03
my 2 accounts survived for while

**Comment by medoamanquer** [comment] 2016-09-30 13:20
Survived

**Comment by exmlcxjv** [comment] 2016-09-30 13:29
2 accs banned, lvl 32 and 33 ,,,, fml

**Comment by gutosales** [comment] 2016-09-30 13:40
It appears to me that my Pokemons list is empty and my level it was 31, 23 are appearing.
this means that I was banned ??
Does anyone know the answer?

**Comment by velwong** [comment] 2016-09-30 13:42
2 accts survived so far still. 
I only stopped after I read the notice which is about 1 day later after the 0.39 is forced.
Keep praying

**Comment by darkKyle** [comment] 2016-09-30 14:04
2 accs, both not banned - both not uses with the bot since force 0.39. ;)

**Comment by Wich0x3** [comment] 2016-09-30 14:15
2 accs banned

**Comment by jdlimajr** [comment] 2016-09-30 14:27
1 acc lvl 31 banned

**Comment by hotmetal007** [comment] 2016-09-30 14:44
tony031 im level 28 in catchem, there is a little trick but im not sure i just do it once,  you know if you visit 10 diferent pokestops on less  30min, the pokestop n°10, will give you the double of items, i got  a 10k egg when i do this on the official app, try to use a route with 10 or more diferent pokestops and eventually you will get a 10km egg.
In catchem is more dificult because the bot will visit all the pokestop and almost ever got an egg before he visit pokestop 10.

**Comment by krummelchen** [comment] 2016-09-30 14:50
since the last update (niantic made the list where you catched the pokemon) they use that feature to check if you are bouncing around the world in short time and running around for hours to farm.

**Comment by QuinnGTL** [comment] 2016-09-30 15:05
I had 3 LVL 25s banned :) I had a 450 charmander candies on one and a couple 100IV pokes i would have likes to trade... oh well! lol. When will the bot be updated for 0.39.1? xD

**Comment by hotmetal007** [comment] 2016-09-30 15:11
krummelchen are you sure?, i was boting on england and central park, but i am from Chile, i allways bot about 8 hours, i stop boting for 2 days when i change beetwen continents

**Comment by krummelchen** [comment] 2016-09-30 15:14
yes iam sure

**Comment by krummelchen** [comment] 2016-09-30 15:19
lost 4 acc 1 with all catchable pokes . i just did 2-3 hours every 2d day and only switched to usa once and of corse australia after 1 week. used proxy server (my own server) and still banned. so only conclusion is the new feature where you found the poke. it also stores time and date poke has been catched with lat. and long.

**Comment by hotmetal007** [comment] 2016-09-30 15:37
😨  then i'm just lucky to not get banned

**Comment by alfath2016** [comment] 2016-09-30 15:40
![capture _2016-09-30-22-35-56](https://cloud.githubusercontent.com/assets/21965034/18997449/9e0cfa00-875e-11e6-9639-96d189aca8f2.png)

Somehow im still a life

**Comment by tiagorossialvolocal** [comment] 2016-09-30 16:04
@alfath2016 botting today and still not banned?

**Comment by rugrus** [comment] 2016-09-30 16:10
36 banned
28 not banned
=/

**Comment by tiagorossialvolocal** [comment] 2016-09-30 16:12
anyone still botting and not bannerd?

**Comment by Wat3v4** [comment] 2016-09-30 16:35
Maybe they made a list and go alphabetically.. so All accounts with the username starting with A, B etc are first to get banned and the ones with Letter Z starting are last.. 
My account starts with L and stil working on my phone..
I stoped using the bot tho the moment the forced update was announced. 

Maybe first they ban PTC accounts and then start google, maybe opposite..
It would help if people state whats the username first letter is and is it PTC or Google.
Also when was last time they used Catchem and are they banned or not.

Mine is L, google. 
Last time 5 days ago(when forced update was announced). 
Not banned.

**Comment by alfath2016** [comment] 2016-09-30 16:39
Yes stiil running till now...
I combined with playing through phone 0.39.1

**Comment by bhumedh** [comment] 2016-09-30 16:48
Today, 3 Account is getting banded

**Comment by kobbey21** [comment] 2016-09-30 17:03
2 acc banned. Lvl 35 and lvl 32. After 3 weeks of botting to get this far. All my hard watch gone to nothing. Lol. Lets start over then

**Comment by HernestoSanchez** [comment] 2016-09-30 18:11
Two acc still alive! Never used catchem after buddy update. Waiting for updated API. Keep calm and wait catchem!

**Comment by Pex972** [comment] 2016-09-30 19:07
lvl 31 banned :(

**Comment by kelsondaleph** [comment] 2016-09-30 20:40
lvl 32 banned =/

**Comment by alanearl** [comment] 2016-09-30 22:04
Just Enjoy its just a GAME :) If your account gets banned just create new... So far no ban since i stop botting after the force update.

**Comment by chadzkiiyaneh** [comment] 2016-10-01 00:58
[08:57:21] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Inventory.<GetPokemons>d__29.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Inventory.<GetHighestsCp>d__18.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 38



What this mean >?

**Comment by LordPyros** [comment] 2016-10-01 01:18
@chadzkiiyaneh - it means your banned.

Can anyone confirm whether or not all botted PTC accounts that have not yet been played on a phone, are banned? Eg accounts that have levelled up but have not choosen a name or caught one of the first 3 pokemon. I have 2 accounts I used on my phone, their fine. The 2 accounts I hadn't transferred yet are goooooone.

**Comment by NeFShARk** [comment] 2016-10-01 01:34
I'm alive! Stop using catchem on my PTC acc since the apk was updated to 0.37.

**Comment by kingkai808** [comment] 2016-10-01 02:19
if you botted after 37 was released you are being banned. simple. all of my accounts are perfectly fine. all my level 30's all 1500 of them not one was banned. you guys just don't know when to stop rofl. on the upside i'll sell you guys a level 30 for 10$ lol

**Comment by kingkai808** [comment] 2016-10-01 02:24
im working on reverse engineering the api from 0.39.1 with a few friends now and hopefully be able to release the new api soon as we are almost done.

**Comment by neokiller89** [comment] 2016-10-01 02:29
Woww.. second ban wave

**Comment by yandraker** [comment] 2016-10-01 03:22
@kingkai808 you have 1500 accounts? wow! hahaha, how is that even possible?

**Comment by kingkai808** [comment] 2016-10-01 03:23
Lots of proxies.

**Comment by tiagorossialvolocal** [comment] 2016-10-01 03:37
Even with lots of proxies its hard to keep each bot into the city of the proxy, you need to check manually each time. If the proxies are paid you can work this out better, if you need to harvest proxies every time you need I think its impossible task to one person alone.

**Comment by kingkai808** [comment] 2016-10-01 03:38
I make 300 at a time. And I used go manager not catchem. I used catchem only in the beginning to accept tos and name it. Then transfer over to go manager to auto rotate proxies. And level.

**Comment by neokiller89** [comment] 2016-10-01 04:40
Haha my account also gt pem ban haha

**Comment by paura123** [comment] 2016-10-01 09:16
got permbanned ç_ç

**Comment by guizinpk** [comment] 2016-10-01 13:55
how do I know i got banned? when I try to log in on catchem this shows "(ERROR) Niantic Servers unstable, throttling API Calls."
And on my phone the loading bar simply doesn't complete.
that's it? I'm permaban?

**Comment by neokiller89** [comment] 2016-10-01 13:57
yup that's it.. perm ban

**Comment by yandraker** [comment] 2016-10-01 14:02
You are using private proxys, right? bought proxies. @kingkai808

**Comment by guizinpk** [comment] 2016-10-01 14:06
yay

**Comment by MixerNaji** [comment] 2016-10-01 21:27
all my accounts banned as perma ! the problem I repaired a lot of things in my laptop to make it work 24h for the bot and this is the gift.

**Comment by davidbung** [comment] 2016-10-01 21:46
10 accounts banned - not sure the reason why? may IP of proxies are in different cities?

**Comment by tiagorossialvolocal** [comment] 2016-10-01 22:53
sure you need IP from same city

**Comment by alfath2016** [comment] 2016-10-02 06:55
5 still healthy...

**Comment by kingkai808** [comment] 2016-10-02 06:57
If u guys need level 30 accounts I still got 10k accounts left.

**Comment by kingkai808** [comment] 2016-10-02 06:58
Yes @yandraker

**Comment by jingyulee** [comment] 2016-10-03 00:52
@guizinpk i also got the message when I try to log in on catchem this shows "(ERROR) Niantic Servers unstable, throttling API Calls."
but i use my ipad login it can login success and then i use my android login .i got the message 
unable to authenticate please try again 
so i do know what happend....

**Comment by NeFShARk** [comment] 2016-10-03 01:58
/\ Catchem is still using api 0.35 and Niantic does not support this version anymore, every device on the planet is\were forced to update pokemon go to 0.39...... Every one using bots that are still using the api 0.35 are getting banned and\or refuse connection to niantic servers.

It to much search a little guys?

**Comment by kingkai808** [comment] 2016-10-03 02:00
Let them not dude they're gonna get banned and more $ for us account sellers hahahahahaha

**Comment by tiagorossialvolocal** [comment] 2016-10-03 02:07
You're banned, try to login into iPhone again and give feedback here
please.
Em 02/10/2016 21:52, "jingyulee" <notifications@github.com> escreveu:

**Comment by alfath2016** [comment] 2016-10-03 11:45
5 still healthy

**Closed** 2016-11-09 10:40 UTC
