### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by AzudemBzudemC** [Lunat1q/Catchem-PoGo#166] opened 2016-08-17 11:28 UTC
[10:50:57] Lapras	- WP: 747  IV: 85,87%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 26)
[10:50:59] Lapras	- WP: 1832  IV: 83,60%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 27)
[10:51:00] Lapras	- WP: 828  IV: 79,67%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 28)
[10:51:01] Lapras	- WP: 1237  IV: 76,30%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 29)
[10:51:02] Lapras	- WP: 1809  IV: 74,57%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 30)
[10:51:04] Lapras	- WP: 2131  IV: 72,13%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 31)
[10:51:05] Lapras	- WP: 1630  IV: 67,97%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 32)
[10:51:06] Lapras	- WP: 1044  IV: 57,73%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 33)
[10:51:08] Lapras	- WP: 1679  IV: 54,34%   [Beste WP: 1781  IV: 97,28%] (Bonbons: 34)
[10:51:09] Nidoking	- WP: 358  IV: 16,22%   [Beste WP: 165  IV: 29,66%] (Bonbons: 16)
[10:51:11] Relaxo	- WP: 1411  IV: 93,91%   [Beste WP: 2704  IV: 97,76%] (Bonbons: 99)
[10:51:12] Relaxo	- WP: 1233  IV: 93,09%   [Beste WP: 2704  IV: 97,76%] (Bonbons: 100)
[10:51:13] Relaxo	- WP: 322  IV: 92,26%   [Beste WP: 2704  IV: 97,76%] (Bonbons: 101)
[10:51:15] Relaxo	- WP: 785  IV: 90,38%   [Beste WP: 2704  IV: 97,76%] (Bonbons: 102)
[10:51:16] Relaxo	- WP: 878  IV: 90,21%   [Beste WP: 2704  IV: 97,76%] (Bonbons: 103)
[10:51:17] Relaxo	- WP: 320  IV: 88,10%   [Beste WP: 2704  IV: 97,76%] (Bonbons: 

my settings:

![unbenannt](https://cloud.githubusercontent.com/assets/21079890/17734718/47d5f4aa-647e-11e6-86b2-29858302b1e3.JPG)

is it a bug or my wrong settings?

**Comment by cbaztos** [comment] 2016-08-17 12:50
hi ,)
i think it s wrong setting =>"prioritize iv above cp"

**Comment by AzudemBzudemC** [comment] 2016-08-17 13:50
If i uncheck "piroritize IV over cp" then the bot keep all pokemon over 1000cp or only 3 Duplikate?

**Comment by xPokemasterx** [comment] 2016-08-17 13:56
AzudemBzudemC better tell us where you got all that Snorlaxes and Relaxos from ? :)

Do you have coordinates for us?

**Comment by AzudemBzudemC** [comment] 2016-08-17 13:59
Pokesniper2 Tool/bot and now pls help me how to solfe my problem

**Comment by AzudemBzudemC** [comment] 2016-08-17 16:00
uncheck  "piroritize IV over cp" dont work, bot also transfer  high cp pokemon und keep only 3 duplicate, i want to set bot keep all pokemon over xxx CP and under xxx CP only 2-3 duplicates.

pls HELP

**Comment by cbaztos** [comment] 2016-08-17 16:16
AzudemBzudemC say:
If i uncheck "piroritize IV over cp" then the bot keep all pokemon over 1000cp or only 3 Duplikate?
---------------------------------------------------------------------------------------------------------------
sorry for my bad english  ;)

but i will say, normally both. he keep all pokemon over 1000 cp with 3 duplicate of the best cp pokemon you have

but he not prefer iv for choice and when the 3 limit attempt come he tranfert the pokemon with bad cp first



but after reflexion,

with your setting the bot do not tranfert  the pokemon above 1000 cp and 70% iv

so finally if you have not change other setting in the pokemon transfert list 

"prioritize iv above cp"  or not 

for me it s a big bug..



ps: with this bot i m just level 23 and i m waiting pokemons cp 700+ for evolve them 

so for now i can not verified if it s work  for me ...

**Comment by AzudemBzudemC** [comment] 2016-08-17 16:36
Bot keep only 3 duplicate! What ever You set => keep   min cp or keep min IV.   

Yes i Know my eng is Very Bad.  SORRY!!!  but i hope everyone Know What i want to say.

**Comment by VforVictory** [comment] 2016-08-18 01:19
Seems like there are some big problems with transferring pokemons. The meaning of "keep min cp" option is that if the cp of a pokemon is higher than the assigned value, this pokemon automatically becomes a "not-to-transfer" pokemon - no matter what other settings say. And this is how the program should work. Yet it transfered 2 of my pokemons with over 1500 cp. By the way, the program has transfered them despite the fact they were favourite (actually, it should not do it). So I hope, the devs will fix these bugs in the next release, because by now I find it impossible to leave the "Transfer Duplicate Pokemon" button checked.

**Comment by shinya88** [comment] 2016-08-18 16:07
This should be a reference to the previous issue #20 which I still find it at the latest release version config.json that have a transfer filter list
Perhaps developer can pull out the transfer filter list during the next release?

**Comment by NotMyProblem** [comment] 2016-08-18 17:21
Guys i had this too you can fix this on your own. See #146
Or for everyone else: Go to Catchem > Profiles > [Name of your Bot] > Config > open config.json with a texteditor go to the far end of the file to "PokemonsTransferFilter": {...} and delete everything between { } of this category.

it´s a hard-coded Transferfilter which overwrites those set in the settings! By deleting them you can avoid such things!

Hopefully helped some before you loose your PKMN!

**Comment by alanearl** [comment] 2016-08-21 02:49
In the Pokemon List Setting Tab.

Add all the Pokemon you don't want to transfer.
Or
Add all your strong pokemon's to favorites.

Good Luck.

**Comment by kingjman1994** [comment] 2016-08-23 20:48
Mine is set up pretty basically the same and my bot never transfers Tauros for some reason. I'm sitting on about 20 or 30 currently. :P

**Comment by fdeleo** [comment] 2016-08-30 13:00
I was having some trouble to understand if it was and OR or AND relationship on the priorities checkboxes, but it seems to be none of them. Maybe it should be clearer when they could conflict and which are related to which (Like inserting the checkboxes related to Pokemon Transfer as a child element as the conditions are)

**Comment by Lunat1q** [comment] 2016-08-31 14:11
should be fixed in next release.

**Closed by Lunat1q** 2016-08-31 14:11 UTC
Labels: bug
