### ISSUE TITLE
[11:43:04] (ERROR) Niantic Servers unstable, throttling API Calls.

### ISSUE THREAD

**Issue by SmokeBlunt** [Lunat1q/Catchem-PoGo#1512] opened 2016-09-07 09:45 UTC
I always get this error, what do i wrong? 
the bot did not start once in the last 3 days

**Comment by Mpako6ec** [comment] 2016-09-07 09:54
+1

**Comment by SmokeBlunt** [comment] 2016-09-07 11:18
And i only have this problem with googleaccounts not with ptc

**Comment by Mpako6ec** [comment] 2016-09-07 12:42
all working

**Comment by HernestoSanchez** [comment] 2016-09-07 13:57
Sup!

Sometimes Ninantic servers are really unstable, thus generating this message.  About the bot not starting. Check your config files. I personally configure all from scretch with each version and it´s really hard to get any error at all.

cya.

**Comment by zhach01** [comment] 2016-09-07 16:29
i used to have this problem but i managed to solved it . now i am boting fine 17 h non stop 0 errors .
some recommendation to solve this problem .
-you must use only one bot / ip .
-one bot / exe ( in case you want multiple account at the same time use vmware or virtual box to creat virtual machines and bot there using proxies or vpn )
-you must use different ipa keys (google directions....) for each bot
-you must make sure that your internet connection can handle the amount of data traffic 
-must have a stable connection  
-in case of server must verify that your firewall is off
-increase the amount of delays 
-keep the max xp under 30000 xp/hour ( untick using lucky egg and auto-evolve)
-keep stardust under 50000 xp/hour 

i hope it could help , have a nice day . @Lunat1q @akira02 @HernestoSanchez @SmokeBlunt @Mpako6ec

**Comment by Sto7mz** [comment] 2016-09-07 22:51
Zhach01


I need to change my delay if you think that works and what should i set the delay to? for the api to go away?

 i got 4 account but i only been botting one for 2days only ands get the api error every 1/2 hour roughly

Regards Matt

**Comment by kaktusisko** [comment] 2016-09-08 01:47
I think that default delays are not like in the official app.
I wrote about this a long time ago.

**Comment by zhach01** [comment] 2016-09-08 05:36
@Sto7mz just multiply the default delays by 2

**Comment by Sto7mz** [comment] 2016-09-08 06:02
@zhach01 not sure what you meant sorry? Could you screenshot your setup please it be really helpful :)

Thanks

**Comment by Lunat1q** [comment] 2016-09-08 08:26
If you get it upon start - try to start this profile with the phone app.

**Comment by Sto7mz** [comment] 2016-09-08 08:35
![save](https://cloud.githubusercontent.com/assets/21327709/18342556/bf849f62-75f2-11e6-9be7-caf75df1a2e0.png)


This what mine is at the moment and i see the api error every 1-2hours now used be 30-1hour.

Im not good with maths so what do i need to change to try fix this api issue? I also tried different ip and it still happens every 1hour roughly.

Im guessing it needs that delay to fix it.

@zhach01 

@Lunat1q

**Comment by zhach01** [comment] 2016-09-08 12:51
@Sto7mz do you run the 2 bots at the same time ? ?

**Comment by Sto7mz** [comment] 2016-09-08 13:00
@zhach01 

And no I got 4 accounts but i dont run more then one bot at a time since too risky.

 I run  one account at a time and give 30mins to- 1 hour before I run the next account and then I don't run them till next day for the accounts I run for 1-2 hours max per account.


I have also tried using it on new ip that isn't connected to my internet and still shows api error.

But it  normally get them alot when it's doing transferring pokemons mainly im guessing it'd transferring too many at once in short amount of time? 

Thanks for getting back to me.

Regards Matt

**Comment by zhach01** [comment] 2016-09-08 13:44
@Sto7mz 
i am now at work i will reply you soon as possible .

**Comment by zhach01** [comment] 2016-09-08 17:07
@Sto7mz
my delay config 32 h non stop 0 errors. i hope could help you if not its something else(like unstable network or a bad configuration of the bot that causes 2 tasks at the same time )

![delay](https://cloud.githubusercontent.com/assets/20936043/18358726/30490704-75ff-11e6-8ab3-4ba0efcdd080.png)

**Comment by madgar29** [comment] 2016-09-08 17:44
last time i got this error was my last ban.... lol

**Comment by Cryptologism** [comment] 2016-09-08 20:41
Actually like @zhach01 and @HernestoSanchez  say.. both them were right.. im using ptc also have this problem somtimes.. Either PTC or Google.. will have this same problem.. Try to do like them said.. All will be okay and make sure.. MAKE SURE your bot look like legit human playing in all aspect...

**Comment by Sto7mz** [comment] 2016-09-08 21:58
@zhach01  Thanks mate i give this a try :)

@madgar29 Yeah not sure my mate did test other night using different bot and got banned in 3hours of being new account without the api so no idea.

I admit this bot by Lunat1q  is the most safest and best bot i have ever used.

**Comment by Sto7mz** [comment] 2016-09-09 00:28
@zhach01

I think its fixed now thanks :) 

I have copied your whole delayed thing and seem to fix the api error all together and i have been running it for 2hours now and no api errors showing up anymore. 

Any idea what the causes of it ?

I let you know how it goes later on.

**Comment by HernestoSanchez** [comment] 2016-09-09 01:00
Yo @zhach01 ! So long!

In my case, when i got this message, a looong time ago, the bot had a very low delay (in the earlier versions). After @Lunat1q released catchem with configurable delay, i left minimum with 5.8 secs and never got this message again. Never because of catchem, i mean, only one day that the servers were unstable. And after i got banned with my first BOB (bot), i always configure everything from scratch, using the SAME phone information, always! For now Bob Father (24) and Bob son (21) are up and running. Never at the same time. I believe eventually they-re going to get banned, but for now, they're alive and kick'n!!!

PS: The first two accounts i had, the ban came just after i fought in some gyns! I didn´t try to dominate any gyn with the actual bots, because im not using the game outside catchem, but, maybe this weekend i do that. If i get banned after leaving a pokemon in a gyn, i believe it have some kind of flag in there. If this happens when, i'll create a post so everyone can share their thoughts.

cya fella!

**Comment by Sto7mz** [comment] 2016-09-09 01:11
@zhach01  And took roughly 4 hours for the error to come up which is a big improvement over 30-1hour.

This what happened.


[10:52:25] (FLEE) (Flee Attempt #2) | Squirtle, Lvl: 7 | CP: (166/450) | IV: 30.86% | Type: Normal | Chance: 22.91% | Dist: 56.00m | Used: GreatBall (1 left) | XP: 0 | 
[10:53:27] (PKMN) Throwing Spinning Normal PokeBall - WILL HIT
[10:53:27] (ESCAPE) (Escape) | Mankey, Lvl: 11 | CP: (248/418) | IV: 58.61% | Type: Normal | Chance: 45.14% | Dist: 35.34m | Used: PokeBall (2 left) | XP: 0 | 
[10:53:38] (PKMN) Throwing Excellent! PokeBall - WILL MISS
[10:53:38] (ESCAPE) (Missed Attempt #2) | Mankey, Lvl: 11 | CP: (248/418) | IV: 58.61% | Type: Normal | Chance: 45.14% | Dist: 35.34m | Used: PokeBall (1 left) | XP: 0 | 
[10:53:48] (PKMN) No Pokeballs - We missed a Mankey with CP 248
[10:55:15] (POKESTOP) Name: The Almighty Man XP: 50, Gems: 0, Items: 3 x ItemPokeBall
[10:56:33] (POKESTOP) Name: Zebo XP: 50, Gems: 0, Items: 1 x ItemPokeBall, 1 x ItemSuperPotion, 1 x ItemRazzBerry
[10:57:31] (POKESTOP) Name: Beach Bean Info Board XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemRazzBerry
[10:59:19] (ERROR) Niantic Servers unstable, throttling API Calls.

**Comment by kreian** [comment] 2016-09-11 15:57
Hi, i have the Error Niantic Servers unstable, throttling API Calls and 

>  (ERROR) System.Net.Http.HttpRequestException: Error al enviar la solicitud. ---> System.Net.WebException: Se ha terminado la conexión: Error inesperado de envío. ---> System.IO.IOException: Se recibió un EOF inesperado o 0 bytes de la secuencia de transporte.
>    en System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
>    en System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
>    en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

**And i only have this problem with ptc not with googleaccounts, and not in my phone norlmal app**

The complete error is:

> [10:43:30] (INFO) Your IP is: 200.85.228.198
> [10:43:30] (UPDATE) Perfecto! Ya tienes la versión más reciente 1.5.2.1
> [10:43:30] (INFO) Logueado usando Ptc
> [10:43:30] (ERROR) System.Net.Http.HttpRequestException: Error al enviar la solicitud. ---> System.Net.WebException: Se ha terminado la conexión: Error inesperado de envío. ---> System.IO.IOException: Se recibió un EOF inesperado o 0 bytes de la secuencia de transporte.
>    en System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
>    en System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
>    en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    en System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() en D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:línea 94
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() en D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:línea 35
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() en D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:línea 55
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    en PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() en D:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:línea 33
> [10:43:30] (INFO) Intentar de nuevo en 45 segundos...
> [10:43:36] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Se produjo una excepción de tipo 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException'.
>    en PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() en D:\catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:línea 79
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() en D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:línea 0
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() en D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:línea 53
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>    en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    en PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() en D:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:línea 259
> [10:43:36] (ATTENTION) Asegúrese de que la Latitud y Longitud son las correctas. Salga del Programa si no es así! Lat: 4,65779572514934 Lng: -74,0933525562286
> [10:43:36] (ERROR) Niantic Servers unstable, throttling API Calls.
> [10:44:01] (ATTENTION) Current Operation was canceled. Bot stopped/paused.

**Comment by Lunat1q** [comment] 2016-09-14 15:43
did a lot of researches... should be fixed

**Closed by Lunat1q** 2016-09-14 15:43 UTC
Labels: help wanted
