### ISSUE TITLE
[Feature Request] Warn When Transferring Favorite Pokemon

### ISSUE THREAD

**Issue by spambox1404** [Lunat1q/Catchem-PoGo#1412] opened 2016-09-05 00:56 UTC
I click on transfer a favourited pokemon by accident and Application transfer it. And I lost it, App should not allow to transfer a favourited pokemon.
Another thing, It should be sort by Number then CP or IV. At the moment, It's just group by Number not in order. 
Thank you!

**Comment by Spk345** [comment] 2016-09-05 04:06
As far as I know, this is not a bug. Changed status to Feature Request.

**Comment by Lunat1q** [comment] 2016-09-05 09:40
You can't transfer fev poke. even manually.

**Comment by Lunat1q** [comment] 2016-09-05 09:47
did small fix with refresh. If u set poke to fav like... 10 secs ago, and try to transfer it, it will allow this, will be fixed in next release.

**Closed by Lunat1q** 2016-09-05 09:47 UTC
