### ISSUE TITLE
[Minor Bug] Poke Markers

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#1482] opened 2016-09-06 16:10 UTC
Poke marker is not ticked but the markers stays.

<a href="http://imgur.com/hsQCw1y"><img src="http://i.imgur.com/hsQCw1y.png" title="source: imgur.com" /></a>

**Comment by Lunat1q** [comment] 2016-09-06 16:22
try to update .net framework...
i can't reproduce that bug to fix it :/

**Comment by lonelies** [comment] 2016-09-06 16:41
at first the markers won't stay. But after leaving the bot running for quite some time, it stays. Weird thing is not all will stay, some will gone. lol

**Comment by lonelies** [comment] 2016-09-06 16:48
framework is up to date.

<a href="http://imgur.com/c4Lq0IC"><img src="http://i.imgur.com/c4Lq0IC.png" title="source: imgur.com" /></a>

**Comment by Lunat1q** [comment] 2016-09-06 16:51
ok, i'll think about the way to hardcheck poke to be removed.

**Comment by lonelies** [comment] 2016-09-06 16:56
in 2 or 3 previous version of catchem, i ticked the "keep poke markers". But when it marked way tooo many cause i run it for hours and sometimes reach 1k poke caught, it somehow crash. I'm not sure if that caused the crash but when i unticked, never crash anymore. That's why i report this one, cause i don't want the marked to be kept. Might crash me again :o

**Comment by Lunat1q** [comment] 2016-09-06 20:27
Got it :) i'll investigate it, closing for now

**Closed by Lunat1q** 2016-09-06 20:27 UTC
